### ISSUE TITLE
Email Notifications for This Free Life

### ISSUE THREAD

**Issue by RescueAgency** [RescueAgencyInternal/Project-Request-App#4]
For both Creative Requests and Staging Requests:

If the Brand field contains “This Free Life” “TFL” or “Free Life” send sari@rescueagency.com and asilva@rescueagency.com the request submitted emails (in addition to still sending to creative ops)

![image](https://user-images.githubusercontent.com/35040134/50710874-198ac200-1021-11e9-9f94-41019ee60266.png)

**Comment by RescueAgency** [comment]
@RescueChris Can I get an ETA on this? Thanks!

**Comment by RescueAgencyMaster** [comment]
@RescueAgency I'll get this updated by EoW with release on Monday, ideally I'll have a system to add custom notifications so it won't require a full re-release with each iteration

**Comment by RescueAgencyMaster** [comment]
Completed, tested, & deployed.  Rather than individually hard coding notifications I've added a system to dynamically link clients to email notifications.  I've already done the notifications for CA/CO for Chris S. & NC for Andy's requests.  I'll be adding all variations for TFL to Sari/ASilva & FE to Bryce today with the intention of in the future adding fuzzy matching instead of exact.
